### ISSUE TITLE
Correct wording

### ISSUE THREAD

**Issue by bryce-carson** [bryce-carson/COMP-2503-001-A1#1]
https://github.com/bryce-carson/COMP-2503-001-A1/blob/530539826a277aa97c7c613a74043048173c8430/src/A2.java#L123

@Velamakanni-Sri-Nandan-Bharadwaj,

The main class does not perform the statistical calculations. Those are completed in A2; main only handles printing (after it calls the utility method/class `A2()`). You already say this, because you documented as such above A2:

>     /**
>      * Initializes the A2 class, processes the input, and calculates word frequencies.
>      */

**Comment by bryce-carson** [comment]
Well, in one way of thinking, main is "responsible" for A2 because it delegates to it, but because it delegates the responsibility the actual work it does is just printing.

**Comment by koddyrae** [comment]
reworded the comment to accurately say what is happening and its correlation to the main class
